language: node_js

node_js:
  - 0.10

before_install:
  - gem install sass compass
  - sass --version

branches:
  except:
    - gh-pages

env:
  global:
    - REPO="git@github.com:g0v/ly.g0v.tw"

    - secure: ! 'Cm2T3ZMpU3GjeAYguwZNMMj9DGCDjZsjiVYuXQ1PgznFG/PpGKcWNaNTt4b9

      pBMRVP7uNtEXfQNcw8TjvG6/HFzuLG4KJeqZUacbbYCRugbny1bDd9iT4OLC

      hnuO6WRsIg4m511XiKHcWu2nFuIFlwCBPS2dSBiRSg8U4Iz9Pqg='

after_success: .travis/after_success.sh
