---
language: node_js

node_js:
  - 0.10

before_install:
  - gem install sass compass
  - sass --version

branches:
  except:
  - gh-pages

deploy:
  on: express_server
  provider: nodejitsu
  user: clkao
  api_key:
    secure: ! 'ZTIUonMOmBRMz5SpI0GvkBLAjoZuq6M4b7flq7HFDAQoaxv6Gok3UOMGmUV6

      mI7uGnLqAggYjWeoIF6yFUIN69hLpIwvfZylOdPU+h/W+H0xlxxtHCvSyc5R

      Ad1AHf93zbf845Cg4LSR0I6fKPewhBW8uFKF5ZYcd7ppofwYrI8='
